In [1]:
import os
import glob
import pandas as pd

In [2]:
file_path = fr"C:\Users\Max\Downloads\nq_bento\data\mt5_nq_final_20160121-0000_20260220-2159.csv"

df = pd.read_csv(file_path)

In [3]:
df.head()

   2016.01.21  00:00  4148.75   4150.0  4146.75  4150.0.1  1.0   67  0.0
0  2016.01.21  00:01  4150.25  4153.75  4149.25   4153.75  1.0   82  0.0
1  2016.01.21  00:02  4153.75  4158.00  4153.50   4156.50  1.0  169  0.0
2  2016.01.21  00:03  4157.00  4165.00  4155.75   4160.00  1.0  358  0.0
3  2016.01.21  00:04  4160.00  4162.75  4159.25   4162.75  1.0   83  0.0
4  2016.01.21  00:05  4162.50  4163.50  4162.00   4162.50  1.0  186  0.0

In [4]:
df.tail(50)

,2016.01.21,00:00,4148.75,4150.0,4146.75,4150.0.1,1.0,67,0.0
3436719,2026.02.20,21:10,25080.00,25082.25,25078.00,25080.00,1.0,396,0.0
3436720,2026.02.20,21:11,25080.00,25081.50,25075.00,25076.75,1.0,319,0.0
3436721,2026.02.20,21:12,25076.50,25078.00,25072.00,25075.00,1.0,441,0.0
3436722,2026.02.20,21:13,25075.25,25081.25,25074.25,25075.75,1.0,350,0.0
3436723,2026.02.20,21:14,25075.25,25079.50,25071.50,25078.50,1.0,214,0.0
3436724,2026.02.20,21:15,25078.50,25078.50,25071.75,25075.00,1.0,153,0.0
3436725,2026.02.20,21:16,25074.50,25074.75,25066.50,25068.00,1.0,210,0.0
3436726,2026.02.20,21:17,25068.00,25073.00,25067.50,25072.75,1.0,105,0.0
3436727,2026.02.20,21:18,25073.00,25074.25,25069.75,25069.75,1.0,62,0.0
3436728,2026.02.20,21:19,25070.00,25071.25,25068.00,25070.75,1.0,95,0.0
3436729,2026.02.20,21:20,25070.50,25074.25,25069.75,25071.50,1.0,96,0.0
3436730,2026.02.20,21:21,25071.25,25071.25,25068.25,25069.25,1.0,62,0.0
3436731,2026.02.20,21:22,25068.75,25069.00,25066.50,25066.50,1.0,99,0.0
3436732,2026.02.20,21:23,25067.25,25071.00,25067.00,25070.25,1.0,82,0.0
3436733,2026.02.20,21:24,25070.00,25071.25,25069.00,25069.50,1.0,48,0.0
3436734,2026.02.20,21:25,25069.25,25069.75,25067.25,25069.75,1.0,63,0.0
3436735,2026.02.20,21:26,25070.00,25070.00,25067.50,25069.25,1.0,100,0.0
3436736,2026.02.20,21:27,25069.00,25070.00,25067.25,25068.50,1.0,69,0.0
3436737,2026.02.20,21:28,25069.00,25070.75,25067.50,25068.75,1.0,62,0.0
3436738,2026.02.20,21:29,25068.50,25070.00,25068.25,25068.50,1.0,52,0.0
3436739,2026.02.20,21:30,25067.75,25070.00,25066.50,25067.50,1.0,68,0.0
3436740,2026.02.20,21:31,25067.25,25072.75,25067.25,25072.75,1.0,131,0.0
3436741,2026.02.20,21:32,25072.50,25073.25,25070.25,25072.25,1.0,125,0.0
3436742,2026.02.20,21:33,25072.25,25072.75,25070.25,25072.00,1.0,44,0.0
3436743,2026.02.20,21:34,25072.00,25073.25,25071.50,25071.75,1.0,57,0.0
3436744,2026.02.20,21:35,25071.50,25073.75,25071.00,25073.00,1.0,82,0.0
3436745,2026.02.20,21:36,25073.25,25074.25,25072.25,25072.25,1.0,56,0.0
3436746,2026.02.20,21:37,25072.00,25072.50,25070.75,25072.50,1.0,50,0.0
3436747,2026.02.20,21:38,25071.75,25075.50,25071.75,25075.25,1.0,69,0.0
3436748,2026.02.20,21:39,25075.00,25075.50,25074.00,25074.50,1.0,47,0.0
3436749,2026.02.20,21:40,25075.00,25075.25,25073.25,25073.75,1.0,85,0.0
3436750,2026.02.20,21:41,25073.25,25075.50,25073.25,25074.75,1.0,39,0.0
3436751,2026.02.20,21:42,25074.50,25075.75,25074.50,25075.25,1.0,44,0.0
3436752,2026.02.20,21:43,25075.50,25079.00,25075.25,25078.75,1.0,113,0.0
3436753,2026.02.20,21:44,25078.75,25079.25,25073.75,25074.00,1.0,126,0.0
3436754,2026.02.20,21:45,25074.50,25077.75,25074.25,25077.00,1.0,75,0.0
3436755,2026.02.20,21:46,25077.00,25078.00,25076.50,25076.75,1.0,37,0.0
3436756,2026.02.20,21:47,25076.75,25077.75,25076.25,25077.25,1.0,62,0.0
3436757,2026.02.20,21:48,25077.00,25077.50,25072.75,25073.50,1.0,71,0.0
3436758,2026.02.20,21:49,25073.75,25076.50,25073.50,25075.00,1.0,67,0.0
3436759,2026.02.20,21:50,25075.25,25076.00,25073.25,25075.75,1.0,51,0.0
3436760,2026.02.20,21:51,25075.50,25076.50,25074.25,25074.25,1.0,61,0.0
3436761,2026.02.20,21:52,25074.25,25075.00,25072.50,25072.50,1.0,60,0.0
3436762,2026.02.20,21:53,25072.25,25072.75,25070.75,25072.00,1.0,43,0.0
3436763,2026.02.20,21:54,25072.50,25079.25,25072.25,25079.00,1.0,176,0.0
3436764,2026.02.20,21:55,25078.00,25081.00,25072.50,25072.50,1.0,171,0.0
3436765,2026.02.20,21:56,25072.75,25073.00,25069.25,25071.75,1.0,112,0.0
3436766,2026.02.20,21:57,25072.00,25073.75,25071.50,25073.50,1.0,25,0.0
3436767,2026.02.20,21:58,25073.25,25079.50,25073.25,25078.25,1.0,62,0.0
3436768,2026.02.20,21:59,25079.00,25079.50,25076.00,25077.50,1.0,108,0.0